{% set name = "dependency_injector" %}
{% set version = "4.48.2" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9ce6089d75a5dd0b6191a243f41d2c2746802bb39550ad431242c15136fefd60

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.1.1                         # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - cython >=3.1.1
  run:
    - python
    - typing-extensions  # [py<311]

test:
  requires:
    - pip
  imports:
    - dependency_injector
    - dependency_injector.ext
  commands:
    - pip check  # [not (osx and arm64)]

about:
  home: https://github.com/ets-labs/python-dependency-injector
  summary: Dependency injection framework for Python
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - gabrielcnr
    - valfvo
