{% set name = "dependency_injector" %}
{% set version = "4.45.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7effdb9e45f5c2813e2fd9dc2ef2c446dd59716f66f9c772ab27b9ed16efc894

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
  run:
    - python
    - six >=1.7.0,<=1.16.0

test:
  imports:
    - dependency_injector
    - dependency_injector.ext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ets-labs/python-dependency-injector
  summary: Dependency injection framework for Python
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - gabrielcnr
