{% set name = "dependency_injector" %}
{% set version = "4.36.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dependency-injector-{{ version }}.tar.gz
  sha256: f0e3c47ec5119508ea16e56db3e20c3db39b85bf0b5971acfc44976b69fc0faa

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - python
    - six >=1.7.0,<=1.16.0

test:
  imports:
    - dependency_injector
    - dependency_injector.ext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ets-labs/python-dependency-injector
  summary: Dependency injection framework for Python
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - gabrielcnr
